name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your primary branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Replaces {{apiKey}} and {{serviceKey}} inside index.html
      - name: Substitute Secrets in index.html
        env:
          APIKEY: ${{ secrets.APIKEY }}
          SERVICEKEY: ${{ secrets.SERVICEKEY }}
        run: |
          sed -i "s|{{apiKey}}|$APIKEY|g" reset-password.html
          sed -i "s|{{serviceKey}}|$SERVICEKEY|g" reset-password.html

      - name: Setup Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
